{{- if .Values.backend.rollout.httpRouteInternal.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "phasor.backend.fullname" . }}-internal
  labels:
    {{- include "phasor.backend.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "phasor.backend.fullname" . }}
      kind: Service
      group: ""
      port: 80
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "phasor.backend.fullname" . }}
          port: 80
        - name: {{ include "phasor.backend.fullname" . }}-canary
          port: 80
{{- end }}
